Domashno 3 i 4/frontend/WineApp/WineApp/Models/ErrorViewModel.cs
namespace WineApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Domashno 3 i 4/frontend/WineApp/WineApp/Models/WineriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using WineApp.Data;

namespace WineApp.Models
{
    public class WineriesController : Controller
    {
        private readonly WineAppContext _context;
        private readonly IHttpClientFactory _httpClientFactory;


        public WineriesController(WineAppContext context, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;

        }

        // GET: Wineries
        public async Task<IActionResult> Index()
        {
            return _context.Winery != null ?
                        View(await _context.Winery.ToListAsync()) :
                        Problem("Entity set 'WineAppContext.Winery'  is null.");
        }

        // GET: Wineries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Winery == null)
            {
                return NotFound();
            }

            var winery = await _context.Winery
                .FirstOrDefaultAsync(m => m.Id == id);
            if (winery == null)
            {
                return NotFound();
            }

            return View(winery);
        }

        // GET: Wineries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Wineries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Winery winery)
        {
            string apiUrl = "http://ec2-16-171-8-88.eu-north-1.compute.amazonaws.com/api/Wineries";

            var httpClient = _httpClientFactory.CreateClient();

            var content = new StringContent(winery.ToJson(), System.Text.Encoding.UTF8, "application/json");

            var response = await httpClient.PostAsync(apiUrl, content);

            if (response.IsSuccessStatusCode)
            {
                string jsonString = await response.Content.ReadAsStringAsync();

                Winery closestWinery = Winery.FromJson(jsonString);

                return View("Details", closestWinery);
            }
            else
            {
                // If the response is not successful, handle the error
                return StatusCode((int)response.StatusCode); // Return the status code as the result
            }
        }

        // POST: Wineries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,lon,lat,name,img,text")] Winery winery)
        {
            if (id != winery.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(winery);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WineryExists(winery.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(winery);
        }

        // GET: Wineries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Winery == null)
            {
                return NotFound();
            }

            var winery = await _context.Winery
                .FirstOrDefaultAsync(m => m.Id == id);
            if (winery == null)
            {
                return NotFound();
            }

            return View(winery);
        }

        // POST: Wineries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Winery == null)
            {
                return Problem("Entity set 'WineAppContext.Winery'  is null.");
            }
            var winery = await _context.Winery.FindAsync(id);
            if (winery != null)
            {
                _context.Winery.Remove(winery);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WineryExists(int id)
        {
            return (_context.Winery?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Domashno 3 i 4/frontend/WineApp/WineApp/Models/Winery.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace WineApp.Models
{
    public class Winery
    {
        [Key]
        public int Id { get; set; }

        public double? lon { get; set; }

        public double? lat { get; set; }

        public String? name { get; set; }

        public String? img { get; set; }
        public String? text { get; set; }

        public static Winery FromJson(string jsonString)
        {
            try
            {
                return JsonConvert.DeserializeObject<Winery>(jsonString);
            }
            catch (Exception ex)
            {
                // Handle exception (e.g., log or throw)
                Console.WriteLine("Error deserializing JSON: " + ex.Message);
                return null;
            }
        }


    }
}

Domashno 3 i 4/frontend/WineApp/WineApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WineApp.Models;

namespace WineApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Domashno 3 i 4/frontend/WineApp/WineApp/Views/Home/Index.cshtml
@using System.Text.Json
@using WineApp.Models

@{
    ViewData["Title"] = "Home Page";
}


<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<style>
    .banner {
        height: 50em;
        background-image: url('https://images.france.fr/zeaejvyq9bhj/2L14hIxac8yqeIcOya6CYs/c8d662037a52f0ccd33fbec9c6eacdb8/1._Wine___Cheese_GL_-_Visuel_Annexe.jpg?w=1120&h=490&q=70&fl=progressive&fit=fill');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: 50%;
    }
</style>
@{
    Winery[] wineries = null;

    string apiUrl = "http://ec2-16-171-8-88.eu-north-1.compute.amazonaws.com/api/Wineries";

    using (var httpClient = new HttpClient())
    {
        var response = await httpClient.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            string jsonResponse = await response.Content.ReadAsStringAsync();

            wineries = JsonSerializer.Deserialize<Winery[]>(jsonResponse);
        }
        else
        {
            Console.WriteLine($"Error: API request failed with status code {response.StatusCode}");
        }
    }
}
<div class="banner text-white">
    <div class="container">
        <nav class="navbar d-flex justify-content-space-between">
            @if (wineries != null)
            {
                foreach (var winery in wineries)
                {
                    <div class="d-flex gap-5" style="margin-top: 1rem;">
                        <span href="#" class="px-2 fw-bold">@winery.name.ToUpper()</span>
                    </div>
                }
            }
        </nav>
        <div class="d-flex justify-content-center align-items-center flex-column">
            <div class="my-5"></div>
            <div class="my-5"></div>
            <p style="font-size: 3rem" class="fw-bold mt-5">MACEDONIAN WINE</p>
            <div class="border-bottom" style="width: 5rem;"></div>
            <h1 style="font-size: 4rem;">MACEDONIAN PRIDE</h1>
            <button class="btn btn-dark rounded-pill border-0 p-3"><i>Taste The Feeling</i></button>
        </div>
    </div>
</div>

<ul>
    @if (wineries != null)
    {
        <div class="bg-white mt-5">
            <div class="container">
                @foreach (var winery in wineries)
                {
                    <div class="row">
                        @* <div class="col-6">
                            <img src="@winery.img" class="img-fluid" style="width: 50rem; height: 25rem;">
                        </div> *@
                        <div class="col-6">
                            <h3 class="text-center mt-5">@winery.name.ToUpper()</h3>
                            <p class="text-center fs-5">@winery.text</p>
                            <div class="d-flex justify-content-center">
                                <button class="btn btn-secondary rounded-pill py-2 px-4 mt-5">@winery.lon - @winery.lat</button>
                            </div>
                        </div>
                    </div>
                    <h1 class="text-center my-5"></h1>
                    <div style="width:100%; height: 4rem;"></div>
                }
            </div>
        </div>
    }
    else
    {
        <p>Loading....</p>
    }
</ul>

Domashno 3 i 4/frontend/WineApp/WineApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WineApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WineApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WineApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Wineries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wineries" asp-action="Create">Location</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WineApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Domashno 3 i 4/frontend/WineApp/WineApp/Views/Wineries/Create.cshtml
@model WineApp.Models.Winery

@{
    ViewData["Title"] = "Create";
}


<h4>Find the Nearest Winery: Enter Your Coordinates</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="lon" class="control-label"></label>
                <input asp-for="lon" class="form-control" />
                <span asp-validation-for="lon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lat" class="control-label"></label>
                <input asp-for="lat" class="form-control" />
                <span asp-validation-for="lat" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Find" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Domashno 3 i 4/frontend/WineApp/WineApp/Views/Wineries/Delete.cshtml
@model WineApp.Models.Winery

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Winery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.img)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.text)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Domashno 3 i 4/frontend/WineApp/WineApp/Views/Wineries/Details.cshtml
@model WineApp.Models.Winery

@{
    ViewData["Title"] = "Closest Winery Near You";
}

<h1>Closest Winery Near You</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.img)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.text)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

Domashno 3 i 4/frontend/WineApp/WineApp/Views/Wineries/Edit.cshtml
@model WineApp.Models.Winery

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Winery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="lon" class="control-label"></label>
                <input asp-for="lon" class="form-control" />
                <span asp-validation-for="lon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lat" class="control-label"></label>
                <input asp-for="lat" class="form-control" />
                <span asp-validation-for="lat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="img" class="control-label"></label>
                <input asp-for="img" class="form-control" />
                <span asp-validation-for="img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="text" class="control-label"></label>
                <input asp-for="text" class="form-control" />
                <span asp-validation-for="text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Domashno 3 i 4/frontend/WineApp/WineApp/Views/Wineries/Index.cshtml
@model IEnumerable<WineApp.Models.Winery>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.lon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.img)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.text)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.lon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.img)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.text)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>